import UIKit

struct StringConstants {
    static let k: String = ""
    static let kLblEatFast: String = "Eat fast"
    static let kLblBack2: String = "Back "
    static let kLblBack: String = "Back"
    static let kLblEnergy: String = "Energy"
    static let kLbl13g: String = "13g\n"
    static let kMsgExperienceThe: String =
        "Experience the comfort of home-cooked meals with the delicious taste"
    static let kLblNext: String = "Next"
    static let kLbl11900: String = "₹ 119.00"
    static let kLbl229: String = "₹ 229."
    static let kLblYourFood: String = "Your Food"
    static let kMsgHealthyBreakfa: String = "healthy breakfast"
    static let kMsgIngredients1: String =
        "Ingredients\r\n1 tbsp olive oil\r\n2 lbs chicken breasts\r\n1/2 tsp kosher salt\r\n1/2 tsp ground black pepper\r\n2 tbsp buttero (if ordered). "
    static let kMsgThankYouForO: String = "Thank You for Ordering !"
    static let kLblAbout: String = "About"
    static let kLblGetStarted2: String = "Get Started"
    static let kLblVegetarian: String = "Vegetarian "
    static let kLblLunch: String = "lunch"
    static let kLbl48: String = "4.8"
    static let kMsgFrenchOnionCh: String = "French Onion Chicken"
    static let kLbl13gFat: String = "13g\nFat"
    static let kLblCalories: String = "\r\nCalories"
    static let kLbl12g: String = "12g\n"
    static let kMsgFrenchOnionC: String = "french Onion  Chicken"
    static let kLblDinner: String = "Dinner"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kMsgOrderYourFavo: String =
        "Order your favorite food from local restaurants and enjoy quick and easy delivery with our user-friendly food app."
    static let kMsgNutritionFacts: String = "Nutrition Facts (per serving)"
    static let kLblDelivery: String = "Delivery"
    static let kLblGetStarted: String = "Get Started!"
    static let kLblCarbs: String = "Carbs"
    static let kLblOrderNow: String = "ORDER NOW"
    static let kLbl41Reviews: String = "(41 Reviews)"
    static let kLblFishSalad: String = "Fish  salad"
    static let kMsgFindWhatYouW: String = "Find what you want...."
    static let kLblCancel: String = "Cancel"
    static let kLblSkip: String = "Skip"
    static let kLblSize: String = "Size"
    static let kLbl: String = ". "
    static let kLblProductDetails: String = "Product details"
    static let kLbl365Calories: String = "365\r\nCalories"
    static let kMsgThePlantBased: String =
        "The plant-based cuisine movement has delivered endless beautiful and wholesome burger recipes, packed with nutrition and flavor. Our vegan gluten-free mushroom burger is just one of the infinite number of choices that vegan cooking has to offer. It is, however, one of the most delicious and easy to make.\nMushrooms are overlooked as a nutritional powerhouse, but they carry "
    static let kMsgFishSaladToma: String = "Fish\nsalad\ntomatoes\nslices,"
    static let kLblMedium: String = "Medium"
    static let kLblSearch: String = "Search"
    static let kLbl1: String = "1"
    static let kLbl2: String = "$2"
    static let kLbl00: String = "00"
    static let kLbl45Min: String = "45 min"
    static let kLbl50gCarbs: String = "50g\nCarbs"
    static let kMsgFoodDeliveryM: String = "Food delivery made easy"
    static let kLbl365: String = "365"
    static let kLblRecentSearch: String = "Recent Search"
    static let kLblChicken: String = "Chicken"
    static let kLblHotPot: String = "Hot Pot"
    static let kMsgSandwichBoil: String = "sandwich, \nboiled egg,\n and tomatoes\n slices,"
    static let kLbl12gProtein: String = "12g\nProtein"
    static let kLblFishSalad2: String = "fish Salad"
    static let kLbl50g: String = "50g\n"
    static let kLblPopular: String = "Popular"
    static let kMsgVeganMushroom: String = "Vegan Mushroom Bean Burger"
    static let kLblBurger: String = "Burger"
    static let kHttpFail: String = "HTTP request failed"
    static let kMsgHomeCookedTas: String = "Home-Cooked Taste"
    static let kLbl22900: String = "₹ 229.00"
    static let kLblProtein: String = "Protein"
    static let kLbl554Kcal: String = "554 KCal"
    static let kLbl119: String = "₹ 119."
    static let kLbl23900: String = "₹ 239.00"
    static let kLblFat: String = "Fat"
    static let kMsgSpendTimeWith: String = "Spend time with loved ones"
    static let kMsgHelpUsImprove: String = " Help us improve by leaving a rating and feedback!"
    static let kMsgIngredients12: String =
        "Ingredients\r\n1 tbsp olive oil\r\n2 lbs chicken breasts\r\n1/2 tsp kosher salt\r\n1/2 tsp ground black pepper\r\n2 tbsp buttero"
    static let kMsgExperienceASp: String =
        "Experience a space close to nature, a variety of vegetarian dishes for you and your loved ones."
    static let kLblRating: String = "Rating"
    static let kLbl239: String = "₹ 239."
    static let kInvalidUrl: String = "Invalid URL"
    static let kLblIfOrdered: String = "(if ordered)"
    static let kLblBreakfast: String = "Breakfast"
}
